export enum PermissionNames {
  TRIP_CREATE = 'TRIP_CREATE',
  TRIP_READ = 'TRIP_READ',
  TRIP_UPDATE = 'TRIP_UPDATE',
  TRIP_DELETE = 'TRIP_DELETE',
  USER_CREATE = 'USER_CREATE',
  USER_READ = 'USER_READ',
  USER_UPDATE = 'USER_UPDATE',
  USER_DELETE = 'USER_DELETE',
}
